isabelle:
  master_dir: 'formalisation/'

gpt-3.5-turbo:
  engine: gpt-3.5-turbo
  api_key: your_api_key

gpt-4o:
  engine: gpt-4o
  api_key: your_api_key

gpt-4:
  engine: gpt-4
  api_key: your_api_key

mistral-small:
  engine: mistral-small-latest
  api_key: your_api_key